# GitGuardian configuration
# https://docs.gitguardian.com/internal-repositories-monitoring/integrations/git_hooks/pre_commit

version: 2

# Paths to ignore during scanning
paths-ignore:
  - "**/test_*.py"          # Test files
  - "**/tests/**"           # Test directories
  - "**/*_test.py"          # Test files pattern
  - "**/.*example"          # Example files
  - "**/.env.example"       # Example environment files
  - "**/docker-compose*.yml" # Docker compose files with test credentials

# Specific secrets to ignore (false positives)
matches-ignore:
  # CI/CD test database credentials (not production)
  - name: CI Test Database Password
    match: test_ci_password_not_production
  - name: CI Test Database Connection String
    match: postgresql://postgres:test_ci_password_not_production
    
  # Development/Example placeholders
  - name: Development Placeholders
    match: changeme
  - name: Example Placeholders
    match: your_password_here
  - name: Example Placeholders
    match: CHANGE_ME
    
  # Already deleted files (in git history)
  - name: Deleted test files
    match: test_auth.py
  - name: Deleted import file
    match: import_security_dashboard.py
  - name: Deleted security suite
    match: security_attack_suite.py

# Detectors to exclude
exclude:
  # No specific detectors excluded - keep all active
  
# Minimum occurrence to trigger (increase for less sensitive detection)
minimum_occurrences: 1

# Custom detectors (optional)
# custom_detectors:
#   - name: Custom Password Pattern
#     regex: 'custom_pattern_here'
